(define (my-sqrt x)
  (define (dist-to-sqrt guess x) (abs (- (* guess guess) x)))
  (define (good-enough? guess x prev)
    (and (< (abs (- (square guess) x)) 0.001)) ( < ( / (abs (- prev guess)) guess) 0.0005))
  (define (average x y) ( / (+ x y) 2))
  (define (improve guess x) (average guess ( / x guess)))
  (define (sqrt-it guess x prev)
	(if (good-enough? guess x prev) guess (sqrt-it (improve guess x) x guess)))
  (sqrt-it 1.0 x 5.0)
)